services:
  database:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: b7web-prisma-blog
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
